import type { GeoLocation } from "~/types";

export const countries: GeoLocation[] = [
  { name: { en: 'Afghanistan', es: 'Afganistán' }, code: 'AF' },
  { name: { en: 'Åland Islands', es: 'Islas Áland' }, code: 'AX' },
  { name: { en: 'Albania', es: 'Albania' }, code: 'AL' },
  { name: { en: 'Algeria', es: 'Argelia' }, code: 'DZ' },
  { name: { en: 'Andorra', es: 'Andorra' }, code: 'AD' },
  { name: { en: 'Angola', es: 'Angola' }, code: 'AO' },
  { name: { en: 'Anguilla', es: 'Anguila' }, code: 'AI' },
  { name: { en: 'Antarctica', es: 'Antártida' }, code: 'AQ' },
  { name: { en: 'Antigua and Barbuda', es: 'Antigua y Barbuda' }, code: 'AG' },
  { name: { en: 'Argentina', es: 'Argentina' }, code: 'AR' },
  { name: { en: 'Armenia', es: 'Armenia' }, code: 'AM' },
  { name: { en: 'Aruba', es: 'Aruba' }, code: 'AW' },
  { name: { en: 'Australia', es: 'Australia' }, code: 'AU' },
  { name: { en: 'Austria', es: 'Austria' }, code: 'AT' },
  { name: { en: 'Azerbaijan', es: 'Azerbaiyán' }, code: 'AZ' },
  { name: { en: 'Bahamas', es: 'Bahamas' }, code: 'BS' },
  { name: { en: 'Bahrain', es: 'Bahréin' }, code: 'BH' },
  { name: { en: 'Bangladesh', es: 'Bangladesh' }, code: 'BD' },
  { name: { en: 'Barbados', es: 'Barbados' }, code: 'BB' },
  { name: { en: 'Belarus', es: 'Bielorrusia' }, code: 'BY' },
  { name: { en: 'Belgium', es: 'Bélgica' }, code: 'BE' },
  { name: { en: 'Belau', es: 'Palaos' }, code: 'PW' },
  { name: { en: 'Belize', es: 'Belice' }, code: 'BZ' },
  { name: { en: 'Benin', es: 'Benín' }, code: 'BJ' },
  { name: { en: 'Bermuda', es: 'Bermudas' }, code: 'BM' },
  { name: { en: 'Bhutan', es: 'Bután' }, code: 'BT' },
  { name: { en: 'Bolivia', es: 'Bolivia' }, code: 'BO' },
  { name: { en: 'Bonaire, Saint Eustatius and Saba', es: 'Bonaire, San Eustaquio y Saba' }, code: 'BQ' },
  { name: { en: 'Bosnia and Herzegovina', es: 'Bosnia y Herzegovina' }, code: 'BA' },
  { name: { en: 'Botswana', es: 'Botsuana' }, code: 'BW' },
  { name: { en: 'Bouvet Island', es: 'Isla Bouvet' }, code: 'BV' },
  { name: { en: 'Brazil', es: 'Brasil' }, code: 'BR' },
  { name: { en: 'British Indian Ocean Territory', es: 'Territorio Británico del Océano Índico' }, code: 'IO' },
  { name: { en: 'British Virgin Islands', es: 'Islas Vírgenes Británicas' }, code: 'VG' },
  { name: { en: 'Brunei', es: 'Brunéi' }, code: 'BN' },
  { name: { en: 'Bulgaria', es: 'Bulgaria' }, code: 'BG' },
  { name: { en: 'Burkina Faso', es: 'Burkina Faso' }, code: 'BF' },
  { name: { en: 'Burundi', es: 'Burundi' }, code: 'BI' },
  { name: { en: 'Cambodia', es: 'Camboya' }, code: 'KH' },
  { name: { en: 'Cameroon', es: 'Camerún' }, code: 'CM' },
  { name: { en: 'Canada', es: 'Canadá' }, code: 'CA' },
  { name: { en: 'Cape Verde', es: 'Cabo Verde' }, code: 'CV' },
  { name: { en: 'Cayman Islands', es: 'Islas Caimán' }, code: 'KY' },
  { name: { en: 'Central African Republic', es: 'República Centroafricana' }, code: 'CF' },
  { name: { en: 'Chad', es: 'Chad' }, code: 'TD' },
  { name: { en: 'Chile', es: 'Chile' }, code: 'CL' },
  { name: { en: 'China', es: 'China' }, code: 'CN' },
  { name: { en: 'Christmas Island', es: 'Isla de Navidad' }, code: 'CX' },
  { name: { en: 'Cocos (Keeling) Islands', es: 'Islas Cocos (Keeling)' }, code: 'CC' },
  { name: { en: 'Colombia', es: 'Colombia' }, code: 'CO' },
  { name: { en: 'Comoros', es: 'Comoras' }, code: 'KM' },
  { name: { en: 'Congo (Brazzaville)', es: 'Congo (Brazzaville)' }, code: 'CG' },
  { name: { en: 'Congo (Kinshasa)', es: 'Congo (Kinshasa)' }, code: 'CD' },
  { name: { en: 'Cook Islands', es: 'Islas Cook' }, code: 'CK' },
  { name: { en: 'Costa Rica', es: 'Costa Rica' }, code: 'CR' },
  { name: { en: 'Croatia', es: 'Croacia' }, code: 'HR' },
  { name: { en: 'Cuba', es: 'Cuba' }, code: 'CU' },
  { name: { en: 'CuraÇao', es: 'Curazao' }, code: 'CW' },
  { name: { en: 'Cyprus', es: 'Chipre' }, code: 'CY' },
  { name: { en: 'Czech Republic', es: 'República Checa' }, code: 'CZ' },
  { name: { en: 'Denmark', es: 'Dinamarca' }, code: 'DK' },
  { name: { en: 'Djibouti', es: 'Yibuti' }, code: 'DJ' },
  { name: { en: 'Dominica', es: 'Dominica' }, code: 'DM' },
  { name: { en: 'Dominican Republic', es: 'República Dominicana' }, code: 'DO' },
  { name: { en: 'Ecuador', es: 'Ecuador' }, code: 'EC' },
  { name: { en: 'Egypt', es: 'Egipto' }, code: 'EG' },
  { name: { en: 'El Salvador', es: 'El Salvador' }, code: 'SV' },
  { name: { en: 'Equatorial Guinea', es: 'Guinea Ecuatorial' }, code: 'GQ' },
  { name: { en: 'Eritrea', es: 'Eritrea' }, code: 'ER' },
  { name: { en: 'Estonia', es: 'Estonia' }, code: 'EE' },
  { name: { en: 'Ethiopia', es: 'Etiopía' }, code: 'ET' },
  { name: { en: 'Falkland Islands', es: 'Islas Malvinas' }, code: 'FK' },
  { name: { en: 'Faroe Islands', es: 'Islas Feroe' }, code: 'FO' },
  { name: { en: 'Fiji', es: 'Fiyi' }, code: 'FJ' },
  { name: { en: 'Finland', es: 'Finlandia' }, code: 'FI' },
  { name: { en: 'France', es: 'Francia' }, code: 'FR' },
  { name: { en: 'French Guiana', es: 'Guayana Francesa' }, code: 'GF' },
  { name: { en: 'French Polynesia', es: 'Polinesia Francesa' }, code: 'PF' },
  { name: { en: 'French Southern Territories', es: 'Territorios Australes y Antárticas Franceses' }, code: 'TF' },
  { name: { en: 'Gabon', es: 'Gabón' }, code: 'GA' },
  { name: { en: 'Gambia', es: 'Gambia' }, code: 'GM' },
  { name: { en: 'Georgia', es: 'Georgia' }, code: 'GE' },
  { name: { en: 'Germany', es: 'Alemania' }, code: 'DE' },
  { name: { en: 'Ghana', es: 'Ghana' }, code: 'GH' },
  { name: { en: 'Gibraltar', es: 'Gibraltar' }, code: 'GI' },
  { name: { en: 'Greece', es: 'Grecia' }, code: 'GR' },
  { name: { en: 'Greenland', es: 'Groenlandia' }, code: 'GL' },
  { name: { en: 'Grenada', es: 'Granada' }, code: 'GD' },
  { name: { en: 'Guadeloupe', es: 'Guadalupe' }, code: 'GP' },
  { name: { en: 'Guatemala', es: 'Guatemala' }, code: 'GT' },
  { name: { en: 'Guernsey', es: 'Guernsey' }, code: 'GG' },
  { name: { en: 'Guinea', es: 'Guinea' }, code: 'GN' },
  { name: { en: 'Guinea-Bissau', es: 'Guinea-Bisáu' }, code: 'GW' },
  { name: { en: 'Guyana', es: 'Guyana' }, code: 'GY' },
  { name: { en: 'Haiti', es: 'Haití' }, code: 'HT' },
  { name: { en: 'Heard Island and McDonald Islands', es: 'Isla Heard y Islas McDonald' }, code: 'HM' },
  { name: { en: 'Honduras', es: 'Honduras' }, code: 'HN' },
  { name: { en: 'Hong Kong', es: 'Hong Kong' }, code: 'HK' },
  { name: { en: 'Hungary', es: 'Hungría' }, code: 'HU' },
  { name: { en: 'Iceland', es: 'Islandia' }, code: 'IS' },
  { name: { en: 'India', es: 'India' }, code: 'IN' },
  { name: { en: 'Indonesia', es: 'Indonesia' }, code: 'ID' },
  { name: { en: 'Iran', es: 'Irán' }, code: 'IR' },
  { name: { en: 'Iraq', es: 'Irak' }, code: 'IQ' },
  { name: { en: 'Republic of Ireland', es: 'Irlanda' }, code: 'IE' },
  { name: { en: 'Isle of Man', es: 'Isla de Man' }, code: 'IM' },
  { name: { en: 'Israel', es: 'Israel' }, code: 'IL' },
  { name: { en: 'Italy', es: 'Italia' }, code: 'IT' },
  { name: { en: 'Ivory Coast', es: 'Costa de Marfil' }, code: 'CI' },
  { name: { en: 'Jamaica', es: 'Jamaica' }, code: 'JM' },
  { name: { en: 'Japan', es: 'Japón' }, code: 'JP' },
  { name: { en: 'Jersey', es: 'Jersey' }, code: 'JE' },
  { name: { en: 'Jordan', es: 'Jordania' }, code: 'JO' },
  { name: { en: 'Kazakhstan', es: 'Kazajistán' }, code: 'KZ' },
  { name: { en: 'Kenya', es: 'Kenia' }, code: 'KE' },
  { name: { en: 'Kiribati', es: 'Kiribati' }, code: 'KI' },
  { name: { en: 'Kuwait', es: 'Kuwait' }, code: 'KW' },
  { name: { en: 'Kyrgyzstan', es: 'Kirguistán' }, code: 'KG' },
  { name: { en: 'Laos', es: 'Laos' }, code: 'LA' },
  { name: { en: 'Latvia', es: 'Letonia' }, code: 'LV' },
  { name: { en: 'Lebanon', es: 'Líbano' }, code: 'LB' },
  { name: { en: 'Lesotho', es: 'Lesoto' }, code: 'LS' },
  { name: { en: 'Liberia', es: 'Liberia' }, code: 'LR' },
  { name: { en: 'Libya', es: 'Libia' }, code: 'LY' },
  { name: { en: 'Liechtenstein', es: 'Liechtenstein' }, code: 'LI' },
  { name: { en: 'Lithuania', es: 'Lituania' }, code: 'LT' },
  { name: { en: 'Luxembourg', es: 'Luxemburgo' }, code: 'LU' },
  { name: { en: 'Macao S.A.R., China', es: 'Macao' }, code: 'MO' },
  { name: { en: 'Macedonia', es: 'Macedonia' }, code: 'MK' },
  { name: { en: 'Madagascar', es: 'Madagascar' }, code: 'MG' },
  { name: { en: 'Malawi', es: 'Malawi' }, code: 'MW' },
  { name: { en: 'Malaysia', es: 'Malasia' }, code: 'MY' },
  { name: { en: 'Maldives', es: 'Maldivas' }, code: 'MV' },
  { name: { en: 'Mali', es: 'Mali' }, code: 'ML' },
  { name: { en: 'Malta', es: 'Malta' }, code: 'MT' },
  { name: { en: 'Marshall Islands', es: 'Islas Marshall' }, code: 'MH' },
  { name: { en: 'Martinique', es: 'Martinica' }, code: 'MQ' },
  { name: { en: 'Mauritania', es: 'Mauritania' }, code: 'MR' },
  { name: { en: 'Mauritius', es: 'Mauricio' }, code: 'MU' },
  { name: { en: 'Mayotte', es: 'Mayotte' }, code: 'YT' },
  { name: { en: 'Mexico', es: 'México' }, code: 'MX' },
  { name: { en: 'Micronesia', es: 'Micronesia' }, code: 'FM' },
  { name: { en: 'Moldova', es: 'Moldavia' }, code: 'MD' },
  { name: { en: 'Monaco', es: 'Mónaco' }, code: 'MC' },
  { name: { en: 'Mongolia', es: 'Mongolia' }, code: 'MN' },
  { name: { en: 'Montenegro', es: 'Montenegro' }, code: 'ME' },
  { name: { en: 'Montserrat', es: 'Montserrat' }, code: 'MS' },
  { name: { en: 'Morocco', es: 'Marruecos' }, code: 'MA' },
  { name: { en: 'Mozambique', es: 'Mozambique' }, code: 'MZ' },
  { name: { en: 'Myanmar', es: 'Myanmar' }, code: 'MM' },
  { name: { en: 'Namibia', es: 'Namibia' }, code: 'NA' },
  { name: { en: 'Nauru', es: 'Nauru' }, code: 'NR' },
  { name: { en: 'Nepal', es: 'Nepal' }, code: 'NP' },
  { name: { en: 'Netherlands', es: 'Países Bajos' }, code: 'NL' },
  { name: { en: 'Netherlands Antilles', es: 'Antillas Neerlandesas' }, code: 'AN' },
  { name: { en: 'New Caledonia', es: 'Nueva Caledonia' }, code: 'NC' },
  { name: { en: 'New Zealand', es: 'Nueva Zelanda' }, code: 'NZ' },
  { name: { en: 'Nicaragua', es: 'Nicaragua' }, code: 'NI' },
  { name: { en: 'Niger', es: 'Níger' }, code: 'NE' },
  { name: { en: 'Nigeria', es: 'Nigeria' }, code: 'NG' },
  { name: { en: 'Niue', es: 'Niue' }, code: 'NU' },
  { name: { en: 'Norfolk Island', es: 'Isla Norfolk' }, code: 'NF' },
  { name: { en: 'North Korea', es: 'Corea del Norte' }, code: 'KP' },
  { name: { en: 'Norway', es: 'Noruega' }, code: 'NO' },
  { name: { en: 'Oman', es: 'Omán' }, code: 'OM' },
  { name: { en: 'Pakistan', es: 'Pakistán' }, code: 'PK' },
  { name: { en: 'Palestinian Territory', es: 'Territorio Palestino' }, code: 'PS' },
  { name: { en: 'Panama', es: 'Panamá' }, code: 'PA' },
  { name: { en: 'Papua New Guinea', es: 'Papúa Nueva Guinea' }, code: 'PG' },
  { name: { en: 'Paraguay', es: 'Paraguay' }, code: 'PY' },
  { name: { en: 'Peru', es: 'Perú' }, code: 'PE' },
  { name: { en: 'Philippines', es: 'Filipinas' }, code: 'PH' },
  { name: { en: 'Pitcairn', es: 'Pitcairn' }, code: 'PN' },
  { name: { en: 'Poland', es: 'Polonia' }, code: 'PL' },
  { name: { en: 'Portugal', es: 'Portugal' }, code: 'PT' },
  { name: { en: 'Qatar', es: 'Qatar' }, code: 'QA' },
  { name: { en: 'Reunion', es: 'Reunión' }, code: 'RE' },
  { name: { en: 'Romania', es: 'Rumania' }, code: 'RO' },
  { name: { en: 'Russia', es: 'Rusia' }, code: 'RU' },
  { name: { en: 'Rwanda', es: 'Ruanda' }, code: 'RW' },
  { name: { en: 'Saint Barthélemy', es: 'San Bartolomé' }, code: 'BL' },
  { name: { en: 'Saint Helena', es: 'Santa Helena' }, code: 'SH' },
  { name: { en: 'Saint Kitts and Nevis', es: 'San Cristóbal y Nieves' }, code: 'KN' },
  { name: { en: 'Saint Lucia', es: 'Santa Lucía' }, code: 'LC' },
  { name: { en: 'Saint Martin (French part)', es: 'San Martín (Parte Francesa)' }, code: 'MF' },
  { name: { en: 'Saint Martin (Dutch part)', es: 'San Martín (Parte Holandesa)' }, code: 'SX' },
  { name: { en: 'Saint Pierre and Miquelon', es: 'San Pedro y Miquelón' }, code: 'PM' },
  { name: { en: 'Saint Vincent and the Grenadines', es: 'San Vicente y las Granadinas' }, code: 'VC' },
  { name: { en: 'San Marino', es: 'San Marino' }, code: 'SM' },
  { name: { en: 'São Tomé and Príncipe', es: 'Santo Tomé y Príncipe' }, code: 'ST' },
  { name: { en: 'Saudi Arabia', es: 'Arabia Saudita' }, code: 'SA' },
  { name: { en: 'Senegal', es: 'Senegal' }, code: 'SN' },
  { name: { en: 'Serbia', es: 'Serbia' }, code: 'RS' },
  { name: { en: 'Seychelles', es: 'Seychelles' }, code: 'SC' },
  { name: { en: 'Sierra Leone', es: 'Sierra Leona' }, code: 'SL' },
  { name: { en: 'Singapore', es: 'Singapur' }, code: 'SG' },
  { name: { en: 'Slovakia', es: 'Eslovaquia' }, code: 'SK' },
  { name: { en: 'Slovenia', es: 'Eslovenia' }, code: 'SI' },
  { name: { en: 'Solomon Islands', es: 'Islas Salomón' }, code: 'SB' },
  { name: { en: 'Somalia', es: 'Somalia' }, code: 'SO' },
  { name: { en: 'South Africa', es: 'Sudáfrica' }, code: 'ZA' },
  { name: { en: 'South Georgia/Sandwich Islands', es: 'Georgia del Sur y las Islas Sandwich del Sur' }, code: 'GS' },
  { name: { en: 'South Korea', es: 'Corea del Sur' }, code: 'KR' },
  { name: { en: 'South Sudan', es: 'Sudán del Sur' }, code: 'SS' },
  { name: { en: 'Spain', es: 'España' }, code: 'ES' },
  { name: { en: 'Sri Lanka', es: 'Sri Lanka' }, code: 'LK' },
  { name: { en: 'Sudan', es: 'Sudán' }, code: 'SD' },
  { name: { en: 'Suriname', es: 'Surinam' }, code: 'SR' },
  { name: { en: 'Svalbard and Jan Mayen', es: 'Svalbard y Jan Mayen' }, code: 'SJ' },
  { name: { en: 'Swaziland', es: 'Suazilandia' }, code: 'SZ' },
  { name: { en: 'Sweden', es: 'Suecia' }, code: 'SE' },
  { name: { en: 'Switzerland', es: 'Suiza' }, code: 'CH' },
  { name: { en: 'Syria', es: 'Siria' }, code: 'SY' },
  { name: { en: 'Taiwan', es: 'Taiwán' }, code: 'TW' },
  { name: { en: 'Tajikistan', es: 'Tayikistán' }, code: 'TJ' },
  { name: { en: 'Tanzania', es: 'Tanzania' }, code: 'TZ' },
  { name: { en: 'Thailand', es: 'Tailandia' }, code: 'TH' },
  { name: { en: 'Timor-Leste', es: 'Timor Oriental' }, code: 'TL' },
  { name: { en: 'Togo', es: 'Togo' }, code: 'TG' },
  { name: { en: 'Tokelau', es: 'Tokelau' }, code: 'TK' },
  { name: { en: 'Tonga', es: 'Tonga' }, code: 'TO' },
  { name: { en: 'Trinidad and Tobago', es: 'Trinidad y Tobago' }, code: 'TT' },
  { name: { en: 'Tunisia', es: 'Túnez' }, code: 'TN' },
  { name: { en: 'Turkey', es: 'Turquía' }, code: 'TR' },
  { name: { en: 'Turkmenistan', es: 'Turkmenistán' }, code: 'TM' },
  { name: { en: 'Turks and Caicos Islands', es: 'Islas Turcas y Caicos' }, code: 'TC' },
  { name: { en: 'Tuvalu', es: 'Tuvalu' }, code: 'TV' },
  { name: { en: 'Uganda', es: 'Uganda' }, code: 'UG' },
  { name: { en: 'Ukraine', es: 'Ucrania' }, code: 'UA' },
  { name: { en: 'United Arab Emirates', es: 'Emiratos Árabes Unidos' }, code: 'AE' },
  { name: { en: 'United Kingdom (UK)', es: 'Reino Unido' }, code: 'GB' },
  { name: { en: 'United States (US)', es: 'Estados Unidos' }, code: 'US' },
  { name: { en: 'Uruguay', es: 'Uruguay' }, code: 'UY' },
  { name: { en: 'Uzbekistan', es: 'Uzbekistán' }, code: 'UZ' },
  { name: { en: 'Vanuatu', es: 'Vanuatu' }, code: 'VU' },
  { name: { en: 'Vatican', es: 'Vaticano' }, code: 'VA' },
  { name: { en: 'Venezuela', es: 'Venezuela' }, code: 'VE' },
  { name: { en: 'Vietnam', es: 'Vietnam' }, code: 'VN' },
  { name: { en: 'Wallis and Futuna', es: 'Wallis y Futuna' }, code: 'WF' },
  { name: { en: 'Western Sahara', es: 'Sahara Occidental' }, code: 'EH' },
  { name: { en: 'Western Samoa', es: 'Samoa Occidental' }, code: 'WS' },
  { name: { en: 'Yemen', es: 'Yemen' }, code: 'YE' },
  { name: { en: 'Zambia', es: 'Zambia' }, code: 'ZM' },
  { name: { en: 'Zimbabwe', es: 'Zimbabue' }, code: 'ZW' },
];

export const delivery_method = {
  STORE_PICKUP: 'STORE_PICKUP',
  DELIVERY: 'DELIVERY',
}
